### ISSUE TITLE
Minor issue specifying external bosh director

### ISSUE THREAD

**Issue by a2geek** [genesis-community/blacksmith-genesis-kit#46]
This is simple to overcome, but the external BOSH director needs more than the suggested configuration. When I only added the configuration:

```
  external_bosh:
    address:  (( vault "secret/exodus/" params.env "/bosh:url"))
    cacert:   (( vault "secret/exodus/" params.env "/bosh:ca_cert"))
    username: (( vault "secret/exodus/" params.env "/bosh:admin_username"))
    password: (( vault "secret/exodus/" params.env "/bosh:admin_password"))
```

I get the following error:

```
STDOUT:
2 error(s) detected:
 - $.meta.external_bosh_password: secret /secret/exodus/gdc-prod/bosh:blacksmith_password not found
 - $.meta.external_bosh_username: secret /secret/exodus/gdc-prod/bosh:blacksmith_user not found
```

Looking at [external-bosh.yml](https://github.com/genesis-community/blacksmith-genesis-kit/blob/21062e80beb36bbc5db12ae82d5f3cefe9e56a4b/manifests/blacksmith/external-bosh.yml#L7-L8), I noted the `meta` references which look for a different name. On a hunch, I tried this:

```
meta:
  external_bosh_password: NOT PRESENT
  external_bosh_username: NOT PRESENT
```

and that works. The text never makes it into the manifest, so it *is* functional...

Is there some more natural method to bypass this hack?

Thanks!
